image:
  file: .gitpod.Dockerfile

tasks:
  - command: >
      dotnet run &&
      dotnet restore &&
      dotnet build

ports:
  - port: 5000
    onOpen: open-preview

vscode:
  extensions:
    - ms-vscode.csharp@1.21.12:kw8SkO8+aVTSFug281WfQQ==